' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package mail {
  class MailService
}

package auto {
  package entity {
    class Auto
  }

  package service #DDDDDD {
    class AutoInvalid
    class ModellExists
    class VersionInvalid
    class VersionOutdated

    class AutoWriteService << control >> <<@Injectable()>> {
      + async create(auto: Auto): Promise<string|AutoInvalid|ModellExists>
      + async update(id: string, auto: Auto, version: string): Promise<number|AutoInvalid|ModellExists|VersionInvalid|VersionOutdated>
      + async delete(id: string): Promise<boolean>
    }

    AutoWriteService o--> "1" AutoValidationService: validationService
    AutoWriteService o--> "1" AutoReadService: readService
    AutoWriteService o--> "1" Repository: @InjectRepository repo
    AutoWriteService o--> "1" MailService: mailService

    AutoWriteService .up.> Injectable
    AutoWriteService .up.> InjectRepository

    AutoWriteService .up.> Promise
    AutoWriteService ..> Auto
    AutoWriteService .up.> AutoInvalid
    AutoWriteService .up.> ModellExists
    AutoWriteService .up.> VersionInvalid
    AutoWriteService .up.> VersionOutdated

    AutoInvalid .up[hidden].> Auto
    Auto .up[hidden].> Promise
    Auto .up[hidden].> Injectable
    Auto .up[hidden].> InjectRepository
    ModellExists .up[hidden].> Auto
    AutoValidationService .[hidden].> Repository
    AutoValidationService .[hidden].> MailService
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
