# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#           skaffold dev
#           skaffold delete

apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: postgres
deploy:
  helm:
    releases:
      - name: postgres
        chartPath: postgres
        valuesFiles: [postgres/values.yaml]
        namespace: acme
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      helm:
        releases:
          - name: postgres
            chartPath: postgres
            valuesFiles: [postgres/values.yaml, postgres/dev.yaml]
            namespace: acme
    portForward:
      - resourceType: service
        resourceName: postgres
        port: postgres-svc
        localPort: 5432
      - resourceType: service
        resourceName: pgadmin
        port: pgadmin-svc
        localPort: 8888
